#! /bin/bash

#VARIABLES
             red='\033[1;31m'                                        green='\033[1;32m'
             yellow='\033[1;33m'                                     blue='\033[1;34m'                                       magenta='\033[1;35m'                                    cyan='\033[1;36m'
             reset='\033[0m'

printf $cyan
echo "
░█░█░█▀█░█░░░▀█▀░░░░░█░░░▀█▀░█▀█░█░█░█░█
░█▀▄░█▀█░█░░░░█░░▄▄▄░█░░░░█░░█░█░█░█░▄▀▄
░▀░▀░▀░▀░▀▀▀░▀▀▀░░░░░▀▀▀░▀▀▀░▀░▀░▀▀▀░▀░▀ "
printf $reset
sleep 1.0
clear
cd 
rm -rf $HOME/VENOM24_KALI.zip

cd $HOME/VENOM24_KALI
apt update -y
apt upgrade -y 
printf $cyan
echo "INSTALANDO KALI-LINUX"
sleep 1.5
printf $reset
pkg install wget openssl-tool proot -y && hash -r && wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/Installer/Kali/kali.sh && bash kali.sh
cd $HOME/VENOM24_KALI/kali-fs/etc
ls
rm -rf bash.bashrc
cd
cp  $HOME/VENOM24_KALI/bash.bashrc $HOME/VENOM24_KALI/kali-fs/etc

cd $HOME/VENOM24_KALI/
./start-kali.sh
